name: cron test

on:
  repository_dispatch:
  workflow_dispatch:

#   schedule:
#     - cron: '0 1 * * *'

jobs:
  cypress-e2e-chrome78-ff70:
    name: Run on Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run smoke:test